# Generated by Django 3.2 on 2021-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.AddField(
            model_name='pizza',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
    ]
